CREATE TABLE EMPREGADO (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(255) NOT NULL,
  DT_ADMISSAO TIMESTAMP,
  SALARIO DECIMAL(8, 2) NOT NULL,
  MATRICULA VARCHAR(255) NOT NULL
) 
